### ISSUE TITLE
La modifica e la cancellazione degli snippet hanno un link rotto

### ISSUE THREAD

**Issue by NonnEmilia** [osmItalia/welcome-tool#2]
Come scritto in talk-it da Andrea Albani nella parte di admin degli snippet i link "modify" e "delete" non vanno perché sono formattati come segue:

    <a href='//admin/snippets/modify/1'>Modify</a> or <a href='//admin/snippets/delete/1'>Delete</a>

Sembra quasi che alla [riga 2](https://github.com/osmItalia/welcome-tool/blob/6ccace490b28d47ee74e1a56dcf7258c35d6add9/views/snippets.php#L2) `Flight::request()->base` si comporti in modo diverso rispetto alle [righe 13 e 14](https://github.com/osmItalia/welcome-tool/blob/6ccace490b28d47ee74e1a56dcf7258c35d6add9/views/snippets.php#L13)...

Nel primo caso sembra essere vuoto e quindi esce correttamente `<a href="/admin/snippets/insert">New snippet</a>`, nel secondo caso sembra che contenga uno `/` e che quindi esca un doppio `/` che dà poi problemi.

**Comment by sabas** [comment]
E' che ho dovuto metterci una pezza ieri sera direttamente sul server e probabilmente non ho aggiornato tutto, adesso controllo :-)
