### ISSUE TITLE
Inserimento note non funziona

### ISSUE THREAD

**Issue by sbiribizio** [osmItalia/welcome-tool#5]
Quando si inserisce una nota ad un utente e si clicca su "Save" si viene reindirizzati a "note/12345"
Manca un / iniziale nel link

**Comment by sbiribizio** [comment]
nel sorgente della pagina HTML delle note vedo:
 
 form method="post" action="//note/5168344"

Ci deve essere un errore a livello di generazione del link

**Comment by NonnEmilia** [comment]
Che sia un problema simile alla issue #2?
